version: '3'
services:
    postgres:
        container_name: postgres
        image: postgres:10.5
    redis:
        container_name: redis
        image: redis:4.0.11
    api:
        container_name: api 
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules # Don't try to override folder, leave as is
            - ./server:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
        depends_on:
            - postgres
    client:
        container_name: client
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
    worker:
        container_name: worker
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /app/node_modules
            - ./worker:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    nginx:
        container_name: nginx
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        restart: always
        ports:
            - 5000:80
        depends_on:
            - api
            - client
